CREATE TABLE UrlEntity (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	type INT NOT NULL,
	hash VARCHAR(96) NOT NULL DEFAULT '',
	name VARCHAR(500) NOT NULL DEFAULT '',
	version VARCHAR(100) NOT NULL DEFAULT '',
	path VARCHAR(500) NOT NULL DEFAULT '',
	
	size VARCHAR(20),
	
	last_visited TIMESTAMP,
	error SMALLINT DEFAULT 0,
	visiting SMALLINT DEFAULT 0,
	visited SMALLINT DEFAULT 0,
	
	PRIMARY KEY (id),
	UNIQUE(type,hash,name,path)
);

CREATE TABLE SearchUrlEntity (
	id INT NOT NULL,
	
	fullUrl VARCHAR(5000) UNIQUE,
	fullUrlLowerCase VARCHAR(5000),
	
	PRIMARY KEY (id),
	FOREIGN KEY (id) REFERENCES UrlEntity (id) ON DELETE CASCADE ON UPDATE RESTRICT
);
