CREATE TABLE SearchUrlEntity (
id INT NOT NULL,

fullUrl VARCHAR(5000) UNIQUE,
fullUrlLowerCase VARCHAR(5000),

PRIMARY KEY (id),
FOREIGN KEY (id) REFERENCES UrlEntity (id) ON DELETE CASCADE ON UPDATE RESTRICT
)